version: '3.6'

services:
  srvdb:
    image: postgres
    container_name: srvdb
    hostname: srvdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: QueryConSql.pwd
      TZ:  America/Guayaquil
    ports:
      - 5632:5432
    networks:
      - datalogger_net
    volumes:
      - pg_data2:/var/lib/postgresql/data

  srvflutter:
    image: sebas1207/front-end
    container_name: srvflutter
    hostname: srvflutter
    environment:
      TZ: America/Guayaquil
    ports:
      - 8080:80
    networks:
      - datalogger_net

  srvwildfly:
    image: sebas1207/back-end
    container_name: srvwildfly
    hostname: srvwildfly
    environment:
      TZ:  America/Guayaquil
    ports:
      - 8082:8080
      - 8899:8009
      - 9992:9990
      - 8787:8787
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -c standalone.xml -bmanagement 0.0.0.0 --debug *:8787
    depends_on:
      - srvdb
    networks:
      - datalogger_net

  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@jasoft.ec
      PGADMIN_DEFAULT_PASSWORD: clave
      TZ:  America/Guayaquil
    ports:
      - 5050:80
    depends_on:
      - srvdb
    networks:
      - datalogger_net
      
  jaegertracingio:
    depends_on:
      - srvwildfly
    image: jaegertracing/all-in-one:1.16.0
    ports:
      - 6831:6831/udp
      - 16686:16686
    networks:
      - datalogger_net

volumes:
  pg_data2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "C:/Users/Pedro Neira/Documents/9no ciclo/Sistemas Distribuidos/docker flutter/volume"

networks:
  datalogger_net: